### ISSUE TITLE
Installation fails on Go 1.18

### ISSUE THREAD

**Issue by ntpeters** [edi9999/path-extractor#10]
Starting in Go 1.18 the `go get` command no longer supports installing packages ([deprecation notice](https://go.dev/doc/go-get-install-deprecation)), and instead now requires using `go install`. However, trying to install `path-extractor` using `go install` fails:

- Specifying the repo:
    ```sh
    $ go install github.com/edi9999/path-extractor@latest
    package github.com/edi9999/path-extractor is not a main package
    ```
- Attempting to point to the path-extractor directory, since `pe.go` is a main package:
    ```sh
    $ go install github.com/edi9999/path-extractor/tree/master/path-extractor@latest
    go: github.com/edi9999/path-extractor/tree/master/path-extractor@latest: module github.com/edi9999/path-extractor@latest found (v0.2.0), but does not contain package github.com/edi9999/path-extractor/tree/master/path-extractor
    ```

**Comment by edi9999** [comment]
Fixed now !
