### ISSUE TITLE
Is it possible to have an absolute path after the process of path-extractor?

### ISSUE THREAD

**Issue by tkt028** [edi9999/path-extractor#3]
Hi Edi,
I have another question. Is it possible to have an absolute path after the process of path-extractor?

Thank you!
Cheers,
Khon

**Comment by edi9999** [comment]
Hi,

I love the unix philosophy and think one tool should do just one job, and do it well. This is why I won't be adding an option to give an absolute path.

However, you can achieve this with a simple pipe:

```
ls | pe | xargs -I{} readlink --canonicalize {}
```

Hope that helps !

**Comment by tkt028** [comment]
Thank you again, Edi. I don't know we have such feature (creating absolute path) in Unix. :D
I am quite satisfied with my config now (tmux, fzf, pe for terminal).

Cheers,
Khon
