### ISSUE TITLE
Possible to handle paths with spaces?

### ISSUE THREAD

**Issue by kergoth** [edi9999/path-extractor#5]
I realize it may be difficult to recognize what's path-like if spaces can be included, particularly since the tool doesn't check for existence on disk, but it may be useful to attempt it, possibly with an optional command-line argument.
 I.e. in my git st in my dotfiles at the moment:

```
?? sublime-text-3/Package Control.ca-bundle
?? sublime-text-3/Package Control.ca-list
```

**Comment by edi9999** [comment]
As a human, I wouldn't be sure that this represents only one file,

it could as well be two files : 

`sublime-text-3/Package`

and 

`Control.ca-bundle`

They would be two ways to recognize it : 

Handle `git status` output specifically, by matching the `??` that is at the beginning of each line

Have a dictionnary of "common" files with spaces, for example "Package Control", maybe with the `--candidates` option proposed in #6

**Comment by kergoth** [comment]
Thanks, that's about what I expected.
